---
# Cisco ASA Firewall Configuration Playbook
# This playbook manages ASA firewall configurations

- name: Configure Cisco ASA Firewalls
  hosts: asa
  gather_facts: no
  connection: network_cli
  
  tasks:
    - name: Display firewall information
      cisco.asa.asa_command:
        commands:
          - show version
          - show inventory
          - show interface ip brief
      register: firewall_info
    
    - name: Print firewall information
      debug:
        var: firewall_info.stdout_lines
    
    - name: Configure NTP servers
      cisco.asa.asa_config:
        lines:
          - ntp server {{ item }}
        loop: "{{ ntp_servers }}"
        save_when: modified
    
    - name: Configure syslog servers
      cisco.asa.asa_config:
        lines:
          - logging host {{ item }}
        loop: "{{ syslog_servers }}"
        save_when: modified
    
    - name: Save running configuration
      cisco.asa.asa_config:
        save_when: always

